//! n2bio/vref2db/src/main.rs

use clap::Parser;
use rusqlite::{params, Connection, Result};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs::File;
use std::io::{BufRead, BufReader};

#[derive(Parser, Debug, Clone)]
#[command(author, version, about = "NCBI Virus-Host Taxonomy DB Builder", long_about = None)]
struct Args {
    /// Name of the SQLite database to create (e.g., taxonomy.db)
    #[arg(long, required = true)]
    db: String,

    /// Path to the JSON report generated by NCBI Datasets
    #[arg(long, required = true)]
    json: String,

    /// Path to the nodes.dmp file
    #[arg(long, required = true)]
    nodes: String,
}


// --- JSON DESERIALIZATION STRUCTS ---
#[derive(Deserialize, Debug)]
struct NcbiNode {
    name: Option<String>,
    tax_id: i64,
}

#[derive(Deserialize, Debug)]
struct TaxonomyData {
    organism_name: Option<String>,
    tax_id: Option<i64>,
    lineage: Option<Vec<NcbiNode>>,
}

#[derive(Deserialize, Debug)]
struct Report {
    accession: String,
    virus: Option<TaxonomyData>,
    host: Option<TaxonomyData>, // Missing for many viral Accession's
}

#[derive(Deserialize, Debug)]
struct NcbiDataset {
    reports: Vec<Report>,
}

// --- DATABASE ROW STRUCTS ---
// Use i64 for compatibility with SQLite integer
#[derive(Debug, Default)]
struct TaxonomyRow {
    accession:       String,
    tax_id:          Option<i64>,
    name:            Option<String>,
    // viral specific ranks
    realm_id:        Option<i64>,
    realm_name:      Option<String>,
    // host specific ranks
    domain_id:       Option<i64>,
    domain_name:     Option<String>,
    // shared ranks
    kingdom_id:      Option<i64>,
    kingdom_name:    Option<String>,
    phylum_id:       Option<i64>,
    phylum_name:     Option<String>,
    subphylum_id:    Option<i64>,
    subphylum_name:  Option<String>,
    class_id:        Option<i64>,
    class_name:      Option<String>,
    subclass_id:     Option<i64>,
    subclass_name:   Option<String>,
    order_id:        Option<i64>,
    order_name:      Option<String>,
    suborder_id:     Option<i64>,
    suborder_name:   Option<String>,
    family_id:       Option<i64>,
    family_name:     Option<String>,
    subfamily_id:    Option<i64>,
    subfamily_name:  Option<String>,
    genus_id:        Option<i64>,
    genus_name:      Option<String>,
    subgenus_id:     Option<i64>,
    subgenus_name:   Option<String>,
    species_id:      Option<i64>,
    species_name:    Option<String>,
    subspecies_id:   Option<i64>,
    subspecies_name: Option<String>,
}

// --- PARSING FUNCTIONS ---

fn load_nodes(path: &str) -> HashMap<i64, String> {
    println!("Loading nodes.dmp...");
    let file: File = File::open(path).expect("Failed to open nodes.dmp");
    let reader: BufReader<File> = BufReader::new(file);
    let mut rank_map: HashMap<i64, String> = HashMap::new();

    for line in reader.lines() {
        let line: String = line.expect("Failed to read line in nodes.dmp");
        let parts: Vec<&str> = line.split("\t|\t").collect();
        if parts.len() >= 3 {
            if let Ok(tax_id) = parts[0].trim().parse::<i64>() {
                let rank = parts[2].trim().to_string();
                rank_map.insert(tax_id, rank);
            }
        }
    }
    println!("Loaded {} taxonomy nodes.", rank_map.len());
    rank_map
}

fn parse_lineage(accession: &str, tax_data: &TaxonomyData, rank_map: &HashMap<i64, String>) -> TaxonomyRow {
    let mut row: TaxonomyRow = TaxonomyRow {
        accession: accession.to_string(),
        tax_id: tax_data.tax_id,
        name: tax_data.organism_name.clone(),
        ..Default::default()
    };

    if let Some(lineage) = &tax_data.lineage {
        for node in lineage {
            if let Some(rank) = rank_map.get(&node.tax_id) {
                match rank.as_str() {
                    "realm" => { row.realm_id = Some(node.tax_id); row.realm_name = node.name.clone(); }
                    "domain" => { row.domain_id = Some(node.tax_id); row.domain_name = node.name.clone(); }
                    "kingdom" => { row.kingdom_id = Some(node.tax_id); row.kingdom_name = node.name.clone(); }
                    "phylum" => { row.phylum_id = Some(node.tax_id); row.phylum_name = node.name.clone(); }
                    "subphylum" => { row.subphylum_id = Some(node.tax_id); row.subphylum_name = node.name.clone(); }
                    "class" => { row.class_id = Some(node.tax_id); row.class_name = node.name.clone(); }
                    "subclass" => { row.subclass_id = Some(node.tax_id); row.subclass_name = node.name.clone(); }
                    "order" => { row.order_id = Some(node.tax_id); row.order_name = node.name.clone(); }
                    "suborder" => { row.suborder_id = Some(node.tax_id); row.suborder_name = node.name.clone(); }
                    "family" => { row.family_id = Some(node.tax_id); row.family_name = node.name.clone(); }
                    "subfamily" => { row.subfamily_id = Some(node.tax_id); row.subfamily_name = node.name.clone(); }
                    "genus" => { row.genus_id = Some(node.tax_id); row.genus_name = node.name.clone(); }
                    "subgenus" => { row.subgenus_id = Some(node.tax_id); row.subgenus_name = node.name.clone(); }
                    "species" => { row.species_id = Some(node.tax_id); row.species_name = node.name.clone(); }
                    "subspecies" => { row.subspecies_id = Some(node.tax_id); row.subspecies_name = node.name.clone(); }
                    _ => {} // Safely ignores any intermediate ranks
                }
            }
        }
    }
    row
}

// --- DATABASE FUNCTIONS ---

fn initialize_database(conn: &Connection) -> Result<()> {
    println!("Initializing SQLite schema...");
    conn.execute_batch(
        "
        PRAGMA foreign_keys = ON;

        CREATE TABLE IF NOT EXISTS viral_taxonomy (
            accession TEXT PRIMARY KEY,
            tax_id INTEGER, name TEXT,
            realm_id INTEGER, realm_name TEXT,
            kingdom_id INTEGER, kingdom_name TEXT,
            phylum_id INTEGER, phylum_name TEXT,
            subphylum_id INTEGER, subphylum_name TEXT,
            class_id INTEGER, class_name TEXT,
            subclass_id INTEGER, subclass_name TEXT,
            order_id INTEGER, order_name TEXT,
            suborder_id INTEGER, suborder_name TEXT,
            family_id INTEGER, family_name TEXT,
            subfamily_id INTEGER, subfamily_name TEXT,
            genus_id INTEGER, genus_name TEXT,
            subgenus_id INTEGER, subgenus_name TEXT,
            species_id INTEGER, species_name TEXT,
            subspecies_id INTEGER, subspecies_name TEXT
        );

        CREATE TABLE IF NOT EXISTS host_taxonomy (
            accession TEXT PRIMARY KEY REFERENCES viral_taxonomy(accession),
            tax_id INTEGER, name TEXT,
            domain_id INTEGER, domain_name TEXT,
            kingdom_id INTEGER, kingdom_name TEXT,
            phylum_id INTEGER, phylum_name TEXT,
            subphylum_id INTEGER, subphylum_name TEXT,
            class_id INTEGER, class_name TEXT,
            subclass_id INTEGER, subclass_name TEXT,
            order_id INTEGER, order_name TEXT,
            suborder_id INTEGER, suborder_name TEXT,
            family_id INTEGER, family_name TEXT,
            subfamily_id INTEGER, subfamily_name TEXT,
            genus_id INTEGER, genus_name TEXT,
            subgenus_id INTEGER, subgenus_name TEXT,
            species_id INTEGER, species_name TEXT,
            subspecies_id INTEGER, subspecies_name TEXT
        );

        CREATE INDEX IF NOT EXISTS idx_viral_tax_id ON viral_taxonomy(tax_id);
        CREATE INDEX IF NOT EXISTS idx_viral_accession ON viral_taxonomy(accession);
        CREATE INDEX IF NOT EXISTS idx_host_tax_id ON host_taxonomy(tax_id);
        CREATE INDEX IF NOT EXISTS idx_host_species_id ON host_taxonomy(species_id);
        "
    )?;
    Ok(())
}

fn insert_viral_rows(conn: &mut Connection, rows: &[TaxonomyRow]) -> Result<()> {
    let tx = conn.transaction()?;
    {
        let mut stmt = tx.prepare(
            "INSERT OR REPLACE INTO viral_taxonomy (
                accession, tax_id, name, realm_id, realm_name, kingdom_id, kingdom_name, 
                phylum_id, phylum_name, subphylum_id, subphylum_name, class_id, class_name, 
                subclass_id, subclass_name, order_id, order_name, suborder_id, suborder_name, 
                family_id, family_name, subfamily_id, subfamily_name, genus_id, genus_name, 
                subgenus_id, subgenus_name, species_id, species_name, subspecies_id, subspecies_name
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28, ?29, ?30, ?31)"
        )?;

        for row in rows {
            stmt.execute(params![
                row.accession, row.tax_id, row.name, row.realm_id, row.realm_name, 
                row.kingdom_id, row.kingdom_name, row.phylum_id, row.phylum_name, 
                row.subphylum_id, row.subphylum_name, row.class_id, row.class_name, 
                row.subclass_id, row.subclass_name, row.order_id, row.order_name, 
                row.suborder_id, row.suborder_name, row.family_id, row.family_name, 
                row.subfamily_id, row.subfamily_name, row.genus_id, row.genus_name, 
                row.subgenus_id, row.subgenus_name, row.species_id, row.species_name, 
                row.subspecies_id, row.subspecies_name
            ])?;
        }
    }
    tx.commit()?;
    Ok(())
}

fn insert_host_rows(conn: &mut Connection, rows: &[TaxonomyRow]) -> Result<()> {
    let tx = conn.transaction()?;
    {
        let mut stmt = tx.prepare(
            "INSERT OR REPLACE INTO host_taxonomy (
                accession, tax_id, name, domain_id, domain_name, kingdom_id, kingdom_name, 
                phylum_id, phylum_name, subphylum_id, subphylum_name, class_id, class_name, 
                subclass_id, subclass_name, order_id, order_name, suborder_id, suborder_name, 
                family_id, family_name, subfamily_id, subfamily_name, genus_id, genus_name, 
                subgenus_id, subgenus_name, species_id, species_name, subspecies_id, subspecies_name
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28, ?29, ?30, ?31)"
        )?;

        for row in rows {
            stmt.execute(params![
                row.accession, row.tax_id, row.name, row.domain_id, row.domain_name, 
                row.kingdom_id, row.kingdom_name, row.phylum_id, row.phylum_name, 
                row.subphylum_id, row.subphylum_name, row.class_id, row.class_name, 
                row.subclass_id, row.subclass_name, row.order_id, row.order_name, 
                row.suborder_id, row.suborder_name, row.family_id, row.family_name, 
                row.subfamily_id, row.subfamily_name, row.genus_id, row.genus_name, 
                row.subgenus_id, row.subgenus_name, row.species_id, row.species_name, 
                row.subspecies_id, row.subspecies_name
            ])?;
        }
    }
    tx.commit()?;
    Ok(())
}

fn main() -> Result<()> {
    let args = Args::parse();

    // 1. Load nodes.dmp
    let rank_map = load_nodes(&args.nodes);

    // 2. Parse the JSON file directly from reader to save memory
    println!("Parsing JSON report: {}", args.json);
    let file = File::open(&args.json).expect("Failed to open JSON file");
    let reader = BufReader::new(file);
    let dataset: NcbiDataset = serde_json::from_reader(reader).expect("Failed to deserialize JSON");

    let mut viral_rows: Vec<TaxonomyRow> = Vec::new();
    let mut host_rows: Vec<TaxonomyRow> = Vec::new();

    // 3. Process the reports
    for report in dataset.reports {
        if let Some(virus_data) = &report.virus {
            viral_rows.push(parse_lineage(&report.accession, virus_data, &rank_map));
        }

        if let Some(host_data) = &report.host {
            host_rows.push(parse_lineage(&report.accession, host_data, &rank_map));
        }
    }

    // 4. Database Operations
    let mut conn: Connection = Connection::open(&args.db)?;
    initialize_database(&conn)?;
    
    println!("Inserting {} viral records...", viral_rows.len());
    insert_viral_rows(&mut conn, &viral_rows)?;

    println!("Inserting {} host records...", host_rows.len());
    insert_host_rows(&mut conn, &host_rows)?;

    println!("Database successfully built at {}", args.db);
    Ok(())
}


