# n2bio/Cargo.toml

[package]
name = "n2bio"
version = "0.1.0"
authors = ["Samuel Bryson <sjbryson@ucla.edu>"]
description = "A rust library for bioinformatics app development"
edition = "2024"
license = "MIT"

[dependencies]
rayon = "1.10"
flate2 = "1.0"
gzp = "0.11"
bzip2 = "0.4"
rustc-hash = "1.1"
byteorder = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
thiserror = "2"
csv = "1.3"

[dev-dependencies]
tempfile = "3.10"